spring.datasource.url=jdbc:h2:mem:store
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
#server.port=8080

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=selfsigned

spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:manufacturer.sql, classpath:client.sql, classpath:employee.sql, classpath:appliance.sql

logging.level.org.springframework.security=DEBUG
logging.level.businessLogger=DEBUG
logging.level.errorLogger=ERROR
logging.level.securityLogger=WARN
logging.level.org.hibernate=ERROR

server.error.whitelabel.enabled=false
server.error.include-exception=true
server.error.include-message=always



